title: Zihao Deng
logo: /assets/me_circle.png
description: Email adress:<br>202221001783@mail.scut.edu.cn<br>scutzihao@foxmail.com<br>[Research gate](https://www.researchgate.net/profile/Zi-Hao-Deng)<br>Research Interest Score:19.5<br>Citations:41<br>h-index:3
#show_downloads: true
theme: jekyll-theme-minimal
